const jokeText = document.getElementById("jokeText");
const jokeButton = document.getElementById("jokeButton");

const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Did you hear about the claustrophobic astronaut? He just needed a little space.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I used to play piano by ear, but now I use my hands.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "How does a penguin build its house? Igloos it together!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
    "I told my wife she was overreacting. She just flipped.",
    "I don't trust stairs because they're always up to something.",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "I'm friends with all electricians. We have such great current connections.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "Why don't scientists trust atoms anymore? Because they make up everything!",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "I used to play piano by ear, but now I use my hands.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to play piano by ear, but now I use my hands.",
    "What do you call a fake noodle? An impasta!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
    "I'm friends with all electricians. We have such great current connections.",
    "How do you organize a space party? You \"planet\"!",
    "Why don't scientists trust atoms anymore? Because they make up everything!",
    "How does a snowman get around? By riding an \"icicle\"!",
    "I don't trust stairs because they're always up to something.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I told my wife she was overreacting. She just flipped.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get from a pampered cow? Spoiled milk!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "I used to be a baker, but I couldn't make enough dough.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call a fish with no eyes? Fsh!",
    "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I'm friends with all electricians. We have such great current connections.",
    "How do you organize a space party? You \"planet\"!",
    "I told my wife she was overreacting. She just flipped.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get from a pampered cow? Spoiled milk!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "I used to play piano by ear, but now I use my hands.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What's orange and sounds like a parrot? A carrot!",
    "I don't trust stairs because they're always up to something.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to play piano by ear, but now I use my hands.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "What's orange and sounds like a parrot? A carrot!",
    "I told my wife she was overreacting. She just flipped.",
    "I'm friends with all electricians. We have such great current connections.",
    "How do you organize a space party? You \"planet\"!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get from a pampered cow? Spoiled milk!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "I used to play piano by ear, but now I use my hands.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What's orange and sounds like a parrot? A carrot!",
    "I don't trust stairs because they're always up to something.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to play piano by ear, but now I use my hands.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "What's orange and sounds like a parrot? A carrot!",
    "I told my wife she was overreacting. She just flipped.",
    "I'm friends with all electricians. We have such great current connections.",
    "How do you organize a space party? You \"planet\"!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get from a pampered cow? Spoiled milk!",
    "What did one wall say to the other wall? I'll meet you at the corner!"
  ];

jokeButton.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * jokes.length);
  jokeText.textContent = jokes[randomIndex];
});
